name: Build and Push Docker Images

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-arm64:
    runs-on: ARM64
    if: github.event_name == 'workflow_dispatch' || contains(github.event.head_commit.message, '#build')
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.MY_PAT_TOKEN }}

      - name: Clone Invidious repository
        run: git clone https://github.com/iv-org/invidious.git

      - name: Get latest version tag from Invidious
        id: get_tag
        run: |
          cd invidious
          LATEST_TAG=$(git describe --tags $(git rev-list --tags --max-count=1))
          echo "LATEST_TAG=$LATEST_TAG" >> $GITHUB_ENV

      - name: Checkout to the latest version tag
        run: |
          cd invidious
          git checkout ${{ env.LATEST_TAG }}

      - name: Build and push arm64 Docker image
        run: |
          cd invidious
          docker buildx create --use
          docker buildx build --platform linux/arm64 \
            --file docker/Dockerfile.arm64 \
            --tag ghcr.io/${{ github.repository }}/invidious:${{ env.LATEST_TAG }}-arm64 \
            --push .

  build-x64:
    runs-on: X64
    if: github.event_name == 'workflow_dispatch' || contains(github.event.head_commit.message, '#build')
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.MY_PAT_TOKEN }}

      - name: Clone Invidious repository
        run: git clone https://github.com/iv-org/invidious.git

      - name: Get latest version tag from Invidious
        id: get_tag
        run: |
          cd invidious
          LATEST_TAG=$(git describe --tags $(git rev-list --tags --max-count=1))
          echo "LATEST_TAG=$LATEST_TAG" >> $GITHUB_ENV

      - name: Checkout to the latest version tag
        run: |
          cd invidious
          git checkout ${{ env.LATEST_TAG }}

      - name: Build and push x64 Docker image
        run: |
          cd invidious
          docker buildx create --use
          docker buildx build --platform linux/amd64 \
            --file docker/Dockerfile \
            --tag ghcr.io/${{ github.repository }}/invidious:${{ env.LATEST_TAG }}-x64 \
            --push .