name: Clone, Commit, Tag, and Build Docker Images

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  check-commit:
    runs-on: ubuntu-latest
    outputs:
      should_run: ${{ steps.check.outputs.should_run }}
    steps:
      - name: Check commit message
        id: check
        run: |
          commit_message=$(git log -1 --pretty=%B)
          if [[ $commit_message == *"[skip ci]"* ]]; then
            echo "should_run=false" >> $GITHUB_OUTPUT
          else
            echo "should_run=true" >> $GITHUB_OUTPUT
          fi

  clone-and-commit:
    needs: check-commit
    if: needs.check-commit.outputs.should_run == 'true'
    runs-on: self-hosted
    outputs:
      latest_tag: ${{ steps.get_tag.outputs.LATEST_TAG }}
    steps:
      - name: Checkout current repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Clone Invidious repository
        run: git clone https://github.com/iv-org/invidious.git invidious-source
      - name: Copy Invidious content to current repository
        run: |
          rsync -a invidious-source/ ./
          git config --global user.email "baris.dogu@icloud.com"
          git config --global user.name "bariiss"
          git add .
          git commit -m "Copied invidious content"
      - name: Get latest version tag from Invidious
        id: get_tag
        run: |
          cd invidious-source
          LATEST_TAG=$(git describe --tags $(git rev-list --tags --max-count=1) || echo "v0.0.0")
          echo "LATEST_TAG=$LATEST_TAG" >> $GITHUB_OUTPUT
      - name: Print latest tag
        run: echo "LATEST_TAG=${{ steps.get_tag.outputs.LATEST_TAG }}"
      - name: Delete the tag if it exists
        env:
          GITHUB_TOKEN: ${{ secrets.MY_PAT_TOKEN }}
        run: |
          if git rev-parse ${{ steps.get_tag.outputs.LATEST_TAG }} >/dev/null 2>&1; then
            git tag -d ${{ steps.get_tag.outputs.LATEST_TAG }}
            git push https://x-access-token:${{ secrets.MY_PAT_TOKEN }}@github.com/${{ github.repository }} :refs/tags/${{ steps.get_tag.outputs.LATEST_TAG }}
          fi
      - name: Create the same tag in the current repository
        env:
          GITHUB_TOKEN: ${{ secrets.MY_PAT_TOKEN }}
        run: |
          git tag ${{ steps.get_tag.outputs.LATEST_TAG }}
          git push https://x-access-token:${{ secrets.MY_PAT_TOKEN }}@github.com/${{ github.repository }} ${{ steps.get_tag.outputs.LATEST_TAG }}

  build-arm64:
    runs-on: ARM64
    needs: clone-and-commit
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Checkout latest tag
        run: |
          git fetch --tags
          git checkout ${{ needs.clone-and-commit.outputs.latest_tag }} || git checkout main
      - name: Print latest tag
        run: echo "LATEST_TAG=${{ needs.clone-and-commit.outputs.latest_tag }}"
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.MY_PAT_TOKEN }}
      - name: Build and push arm64 Docker image with version and latest tags
        run: |
          docker buildx create --use
          docker buildx build --platform linux/arm64 \
            --file docker/Dockerfile.arm64 \
            --tag ghcr.io/${{ github.repository }}:${{ needs.clone-and-commit.outputs.latest_tag }}-arm64 \
            --tag ghcr.io/${{ github.repository }}:latest-arm64 \
            --push .

  build-x64:
    runs-on: X64
    needs: clone-and-commit
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Checkout latest tag
        run: |
          git fetch --tags
          git checkout ${{ needs.clone-and-commit.outputs.latest_tag }} || git checkout main
      - name: Print latest tag
        run: echo "LATEST_TAG=${{ needs.clone-and-commit.outputs.latest_tag }}"
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.MY_PAT_TOKEN }}
      - name: Build and push x64 Docker image with version and latest tags
        run: |
          docker buildx create --use
          docker buildx build --platform linux/amd64 \
            --file docker/Dockerfile \
            --tag ghcr.io/${{ github.repository }}:${{ needs.clone-and-commit.outputs.latest_tag }}-x64 \
            --tag ghcr.io/${{ github.repository }}:latest-x64 \
            --push .

  final-commit:
    needs: [check-commit, build-arm64, build-x64]
    if: needs.check-commit.outputs.should_run == 'true'
    runs-on: self-hosted
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v3
        with:
          ref: main
          fetch-depth: 0
      - name: Commit and push changes
        run: |
          git config --global user.email "baris.dogu@icloud.com"
          git config --global user.name "bariiss"
          git add .
          git diff --staged --quiet || git commit -m "Update main repository after successful builds [skip ci]"
          git push https://x-access-token:${{ secrets.MY_PAT_TOKEN }}@github.com/${{ github.repository }} main