name: Build and Push Docker Images

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-arm64:
    runs-on: patrick
    if: github.event_name == 'workflow_dispatch' || contains(github.event.head_commit.message, '#build')
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.MY_PAT_TOKEN }}
      
      - name: Clone Invidious repository
        run: git clone https://github.com/iv-org/invidious.git
      
      - name: Build and push arm64 Docker image
        run: |
          cd invidious
          docker buildx create --use
          docker buildx build --platform linux/arm64 \
            --file docker/Dockerfile.arm64 \
            --tag ghcr.io/${{ github.repository }}/invidious:arm64-latest \
            --push .

  build-x64:
    runs-on: vultr
    if: github.event_name == 'workflow_dispatch' || contains(github.event.head_commit.message, '#build')
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.MY_PAT_TOKEN }}
      
      - name: Clone Invidious repository
        run: git clone https://github.com/iv-org/invidious.git
      
      - name: Build and push x64 Docker image
        run: |
          cd invidious
          docker buildx create --use
          docker buildx build --platform linux/amd64 \
            --file docker/Dockerfile \
            --tag ghcr.io/${{ github.repository }}/invidious:x64-latest \
            --push .