name: Build and Push Docker Images

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-arm64:
    runs-on: squidward
    if: github.event_name == 'workflow_dispatch' || contains(github.event.head_commit.message, '#build')
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.MY_PAT_TOKEN }}
      
      - name: Clone Invidious repository
        run: git clone https://github.com/iv-org/invidious.git
      
      - name: Build and push arm64 image
        uses: docker/build-push-action@v4
        with:
          context: ./invidious
          file: ./invidious/docker/Dockerfile.arm64
          platforms: linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/${{ github.repository }}:latest-arm64
          build-args: |
            BUILDPLATFORM=linux/arm64
            NO_CACHE=true
          provenance: false

  build-x64:
    runs-on: contabo-l
    if: github.event_name == 'workflow_dispatch' || contains(github.event.head_commit.message, '#build')
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.MY_PAT_TOKEN }}
      
      - name: Clone Invidious repository
        run: git clone https://github.com/iv-org/invidious.git
      
      - name: Build and push x64 image
        uses: docker/build-push-action@v4
        with:
          context: ./invidious
          file: ./invidious/docker/Dockerfile
          platforms: linux/amd64
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/${{ github.repository }}:latest-amd64
          build-args: |
            BUILDPLATFORM=linux/amd64
            NO_CACHE=true
          provenance: false