name: Build and Push Docker Images

on:
  push:
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  set-latest-tag:
    runs-on: self-hosted
    if: github.event_name == 'workflow_dispatch' || contains(github.event.head_commit.message, '#build')
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Get latest tag
        id: get_latest_tag
        run: echo "LATEST_TAG=$(git describe --tags --abbrev=0)" >> $GITHUB_OUTPUT

      - name: Set latest tag to vars
        run: echo "LATEST_TAG=${{ steps.get_latest_tag.outputs.LATEST_TAG }}" >> $GITHUB_VARS

  build-arm64:
    needs: set-latest-tag
    runs-on: squidward
    if: github.event_name == 'workflow_dispatch' || contains(github.event.head_commit.message, '#build')
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.MY_PAT_TOKEN }}
      
      - name: Clone Invidious repository
        run: git clone https://github.com/iv-org/invidious.git
      
      - name: Build and push arm64 image
        uses: docker/build-push-action@v4
        with:
          context: ./invidious
          file: ./invidious/docker/Dockerfile.arm64
          platforms: linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/${{ github.repository }}:latest-arm64
          build-args: |
            BUILDPLATFORM=linux/arm64
            NO_CACHE=true
          cache-from: type=gha
          cache-to: type=gha,mode=max
          provenance: false

  build-x64:
    needs: set-latest-tag
    runs-on: contabo-l
    if: github.event_name == 'workflow_dispatch' || contains(github.event.head_commit.message, '#build')
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.MY_PAT_TOKEN }}
      
      - name: Clone Invidious repository
        run: git clone https://github.com/iv-org/invidious.git
      
      - name: Build and push x64 image
        uses: docker/build-push-action@v4
        with:
          context: ./invidious
          file: ./invidious/docker/Dockerfile
          platforms: linux/amd64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}:latest-amd64
          build-args: |
            BUILDPLATFORM=linux/amd64
            NO_CACHE=true
          cache-from: type=gha
          cache-to: type=gha,mode=max
          provenance: false