name: Build and Push Docker Images

on:
  push:
    branches:
      - main
    paths:
      - Dockerfile*
  workflow_dispatch:

jobs:
  build-arm64:
    runs-on: ARM64
    if: github.event_name == 'workflow_dispatch' || contains(github.event.head_commit.message, '#build')
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.MY_PAT_TOKEN }}

      - name: Download Dockerfile for arm64
        run: wget https://raw.githubusercontent.com/iv-org/invidious/master/docker/Dockerfile.arm64 -O Dockerfile

      - name: Build and push arm64 Docker image
        run: |
          docker buildx create --use
          docker buildx build --platform linux/arm64 \
            --file Dockerfile \
            --tag ghcr.io/${{ github.repository }}/invidious:arm64-latest \
            --push .

  build-x64:
    runs-on: X64
    if: github.event_name == 'workflow_dispatch' || contains(github.event.head_commit.message, '#build')
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Download Dockerfile for x64
        run: wget https://raw.githubusercontent.com/iv-org/invidious/master/docker/Dockerfile -O Dockerfile

      - name: Build and push x64 Docker image
        run: |
          docker buildx create --use
          docker buildx build --platform linux/amd64 \
            --file Dockerfile \
            --tag ghcr.io/${{ github.repository }}/invidious:x64-latest \
            --push .
